version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8071:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3000
      - APP_PASSWORD=admin
      - JWT_SECRET=zammad_budget_jwt_secret_2024
      - ZAMMAD_URL=https://michaelguggenbichler.com
      - ZAMMAD_TOKEN=tKhj4Lr5xbXELe_reoKX3HZNw8gtU2ig7vBUTEsgWCSJPE_4dovYvH0ms7s5upT4
      - DEBUG_LVL=debug
    volumes:
      - zammad-data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  zammad-data: