version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8071:80"  # Frontend
      - "3071:3000"  # Backend API
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/data/dev.db
      - ZAMMAD_URL=${ZAMMAD_URL}
      - ZAMMAD_TOKEN=${ZAMMAD_TOKEN}
      - APP_PASSWORD=${APP_PASSWORD:-admin}
      - JWT_SECRET=${JWT_SECRET:-development-secret}
      - CORS_ALLOWED_ORIGINS=http://localhost:8071,http://localhost:3071
    volumes:
      - zammad_budget_data:/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - zammad_budget_net

networks:
  zammad_budget_net:
    driver: bridge

volumes:
  zammad_budget_data:
    driver: local