version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8071:80"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=/api
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3071:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=file:/data/dev.db
      - JWT_SECRET=${JWT_SECRET}
      - APP_PASSWORD=${APP_PASSWORD}
      - ZAMMAD_URL=${ZAMMAD_URL}
      - ZAMMAD_TOKEN=${ZAMMAD_TOKEN}
    volumes:
      - ./data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data:
    driver: local