version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3000
      - ZAMMAD_URL=${ZAMMAD_URL}
      - ZAMMAD_TOKEN=${ZAMMAD_TOKEN}
      - APP_PASSWORD=${APP_PASSWORD:-admin}
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret_here_make_it_long_and_secure}
    volumes:
      - ./backend/prisma/dev.db:/app/prisma/dev.db
    restart: unless-stopped
    platform: linux/amd64
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://backend:3000
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    platform: linux/amd64
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  default:
    driver: bridge

volumes:
  db-data:
    driver: local