version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3071
      - ZAMMAD_URL=${ZAMMAD_URL}
      - ZAMMAD_TOKEN=${ZAMMAD_TOKEN}
      - APP_PASSWORD=${APP_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=file:/data/dev.db
    volumes:
      - ./data:/data
    ports:
      - "3071:3071"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3071/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8071:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=/api
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  data: