version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3000
      - ZAMMAD_URL=${ZAMMAD_URL}
      - ZAMMAD_TOKEN=${ZAMMAD_TOKEN}
      - APP_PASSWORD=${APP_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=file:/data/dev.db
      - DEBUG_LVL=debug
    volumes:
      - /mnt/user/appdata/zammad-budget:/data
    ports:
      - "8071:80"
      - "3071:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s