name: Docker Build and Publish

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      build_tag:
        description: 'Custom tag for the Docker image (optional)'
        required: false
        default: 'latest'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  NODE_VERSION: '20'
  LOCAL_IMAGE_NAME: zammad-budget:test

jobs:
  test-and-scan:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          cd frontend && npm ci
          cd ../backend && npm ci

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build local image for scanning
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ${{ env.LOCAL_IMAGE_NAME }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Create scan results directory
        run: mkdir -p scan-results

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.LOCAL_IMAGE_NAME }}
          format: 'sarif'
          output: 'scan-results/trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          scanners: vuln

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'scan-results/trivy-results.sarif'
          category: 'trivy'

  build-and-push:
    needs: test-and-scan
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cosign
        uses: sigstore/cosign-installer@v3.3.0

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,format=long
            type=raw,value=${{ github.event.inputs.build_tag || 'latest' }},enable={{is_default_branch}}
          labels: |
            org.opencontainers.image.title=Zammad Budget Manager
            org.opencontainers.image.description=Track and manage time budgets for Zammad organizations
            org.opencontainers.image.vendor=ghotso
            org.opencontainers.image.version=${{ github.ref_name }}
            org.opencontainers.image.created=${{ github.event.repository.updated_at }}
            org.opencontainers.image.licenses=MIT
            com.github.repo=ghotso/zammad-budget
            com.github.sha=${{ github.sha }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
          build-args: |
            NODE_ENV=production
            VITE_APP_VERSION=${{ github.ref_name }}
            BUILD_TIMESTAMP=${{ github.event.repository.updated_at }}
            BUILDPLATFORM=${{ runner.arch }}
            TARGETPLATFORM=${{ runner.arch }}

      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: echo "${{ steps.meta.outputs.tags }}" | xargs -I {} cosign sign --yes {}

      - name: Update container description
        if: github.event_name != 'pull_request'
        uses: peter-evans/dockerhub-description@v3
        with:
          registry: ghcr.io
          repository: ghotso/zammad-budget
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
          readme-filepath: ./README.md
          short-description: "Zammad Budget Manager - Track and manage time budgets for Zammad organizations"

  notify:
    needs: build-and-push
    if: always()
    runs-on: ubuntu-24.04
    steps:
      - name: Update status badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        continue-on-error: true
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: ${{ secrets.GIST_ID }}
          filename: zammad-budget-build.json
          label: build
          message: ${{ needs.build-and-push.result == 'success' && 'passing' || 'failing' }}
          color: ${{ needs.build-and-push.result == 'success' && 'success' || 'critical' }}